// Comprehensive KPI datasets for all 4 personas
// Supporting main dashboard (priority 1-4) + insights tab (priority 5-25)

interface KpiData {
  id: string;
  kpiName: string;
  currentValue: string;
  previousValue: string;
  target: string;
  unit: string;
  category: string;
  trend: 'improving' | 'declining' | 'stable' | 'up' | 'down';
  context: 'main_dashboard' | 'insights_tab';
  displayContext: 'main' | 'insights' | 'both';
  priority: number;
  viewCategory: 'technical' | 'business' | 'both';
  personaRelevance: string[];
  description?: string;
}

// ============================================================================
// ADMIN (JARVIS System Administrator) - 24 KPIs Total
// ============================================================================
export function generateComprehensiveAdminKpis(
  emails: any[] = [],
  activities: any[] = [],
  submissions: any[] = []
): KpiData[] {
  const totalAgentExecutions = activities.filter((a: any) => 
    a.activity.toLowerCase().includes('agent') || a.activity.toLowerCase().includes('execution')
  ).length;
  const processingEmails = emails.filter((e: any) => e.processingStatus === 'processing').length;

  return [
    // ===== MAIN DASHBOARD (Priority 1-4) =====
    {
      id: 'admin-orchestration-rate',
      kpiName: 'Agent Orchestration Rate',
      currentValue: totalAgentExecutions.toString(),
      previousValue: Math.max(0, totalAgentExecutions - 3).toString(),
      target: '50',
      unit: 'executions/hr',
      category: 'meta_brain',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 1,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'Real-time agent execution and orchestration performance'
    },
    {
      id: 'admin-system-health-score',
      kpiName: 'System Health Score',
      currentValue: '94.2',
      previousValue: '91.8',
      target: '95.0',
      unit: '%',
      category: 'system',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 2,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'Overall system health and stability metrics'
    },
    {
      id: 'admin-total-submissions',
      kpiName: 'Total Submissions',
      currentValue: submissions.length.toString(),
      previousValue: Math.max(0, submissions.length - 2).toString(),
      target: '100',
      unit: 'submissions',
      category: 'productivity',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 3,
      viewCategory: 'business',
      personaRelevance: ['admin', 'rachel', 'broker'],
      description: 'Total processed submissions across all workflows'
    },
    {
      id: 'admin-platform-efficiency',
      kpiName: 'Platform Efficiency',
      currentValue: processingEmails > 0 ? '87.4' : '89.4',
      previousValue: '87.2',
      target: '90.0',
      unit: '%',
      category: 'performance',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 4,
      viewCategory: 'business',
      personaRelevance: ['admin', 'john', 'rachel'],
      description: 'Overall platform operational efficiency'
    },

    // ===== INSIGHTS TAB (Priority 5-25) =====
    {
      id: 'admin-agent-performance-matrix',
      kpiName: 'Agent Performance Matrix',
      currentValue: '8.7',
      previousValue: '8.2',
      target: '9.0',
      unit: 'score',
      category: 'meta_brain',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 5,
      viewCategory: 'technical',
      personaRelevance: ['admin'],
      description: 'Comprehensive agent performance scoring'
    },
    {
      id: 'admin-resource-utilization',
      kpiName: 'Resource Utilization',
      currentValue: '76.3',
      previousValue: '72.1',
      target: '80.0',
      unit: '%',
      category: 'system',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 6,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'System resource utilization efficiency'
    },
    {
      id: 'admin-security-metrics',
      kpiName: 'Security Score',
      currentValue: '98.1',
      previousValue: '97.6',
      target: '99.0',
      unit: '%',
      category: 'security',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 7,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'Comprehensive security posture metrics'
    },
    {
      id: 'admin-cost-analytics',
      kpiName: 'Cost Analytics',
      currentValue: '3.2M',
      previousValue: '3.8M',
      target: '2.8M',
      unit: 'USD',
      category: 'business',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 8,
      viewCategory: 'business',
      personaRelevance: ['admin'],
      description: 'Operational cost reduction through automation'
    },
    {
      id: 'admin-user-engagement',
      kpiName: 'User Engagement',
      currentValue: '84.6',
      previousValue: '81.2',
      target: '88.0',
      unit: '%',
      category: 'experience',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 9,
      viewCategory: 'business',
      personaRelevance: ['admin'],
      description: 'Platform user engagement and satisfaction'
    },
    {
      id: 'admin-system-diagnostics',
      kpiName: 'System Diagnostics',
      currentValue: '142',
      previousValue: '158',
      target: '120',
      unit: 'ms',
      category: 'performance',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 10,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'System diagnostic response times'
    },
    {
      id: 'admin-workflow-automation',
      kpiName: 'Workflow Automation',
      currentValue: '92.3',
      previousValue: '89.1',
      target: '95.0',
      unit: '%',
      category: 'productivity',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 11,
      viewCategory: 'business',
      personaRelevance: ['admin', 'rachel', 'john'],
      description: 'Percentage of fully automated workflows'
    },
    {
      id: 'admin-data-quality',
      kpiName: 'Data Quality Score',
      currentValue: '96.7',
      previousValue: '94.8',
      target: '97.5',
      unit: '%',
      category: 'data',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 12,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'rachel'],
      description: 'Overall data quality and consistency metrics'
    },
    {
      id: 'admin-integration-health',
      kpiName: 'Integration Health',
      currentValue: '99.2',
      previousValue: '98.7',
      target: '99.5',
      unit: '%',
      category: 'integration',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 13,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'Third-party integration stability and performance'
    },
    {
      id: 'admin-sla-compliance',
      kpiName: 'SLA Compliance',
      currentValue: '97.8',
      previousValue: '96.2',
      target: '98.5',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 14,
      viewCategory: 'business',
      personaRelevance: ['admin', 'john'],
      description: 'Service level agreement compliance rate'
    },
    {
      id: 'admin-scalability-index',
      kpiName: 'Scalability Index',
      currentValue: '8.4',
      previousValue: '7.9',
      target: '9.0',
      unit: 'index',
      category: 'system',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 15,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'System scalability and growth readiness'
    },
    {
      id: 'admin-api-performance',
      kpiName: 'API Performance',
      currentValue: '178',
      previousValue: '192',
      target: '150',
      unit: 'ms',
      category: 'performance',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 16,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'Average API response time performance'
    },
    {
      id: 'admin-error-recovery',
      kpiName: 'Error Recovery Rate',
      currentValue: '94.6',
      previousValue: '91.8',
      target: '96.0',
      unit: '%',
      category: 'reliability',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 17,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'Automatic error recovery success rate'
    },
    {
      id: 'admin-compliance-score',
      kpiName: 'Compliance Score',
      currentValue: '97.2',
      previousValue: '96.1',
      target: '98.0',
      unit: '%',
      category: 'governance',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 18,
      viewCategory: 'business',
      personaRelevance: ['admin'],
      description: 'Regulatory compliance score'
    },
    {
      id: 'admin-throughput',
      kpiName: 'System Throughput',
      currentValue: '2,847',
      previousValue: '2,632',
      target: '3,000',
      unit: 'req/min',
      category: 'performance',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 19,
      viewCategory: 'technical',
      personaRelevance: ['admin', 'john'],
      description: 'System processing throughput rate'
    },
    {
      id: 'admin-revenue-impact',
      kpiName: 'Revenue Impact',
      currentValue: '8.7M',
      previousValue: '7.9M',
      target: '10.0M',
      unit: 'USD',
      category: 'business',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 20,
      viewCategory: 'business',
      personaRelevance: ['admin'],
      description: 'Direct revenue impact from platform automation'
    }
  ];
}

// ============================================================================
// RACHEL THOMPSON (AUW) - 24 KPIs Total
// ============================================================================
export function generateComprehensiveRachelKpis(
  emails: any[] = [],
  activities: any[] = [],
  submissions: any[] = [],
  commercialSubmissions: any[] = []
): KpiData[] {
  const processedEmails = emails.filter((e: any) => e.processingStatus === 'completed');
  const failedEmails = emails.filter((e: any) => e.processingStatus === 'failed');

  return [
    // ===== MAIN DASHBOARD (Priority 1-4) =====
    {
      id: 'rachel-documents-submitted',
      kpiName: 'Documents Submitted',
      currentValue: commercialSubmissions.length.toString(),
      previousValue: Math.max(0, commercialSubmissions.length - 2).toString(),
      target: '15',
      unit: 'submissions',
      category: 'productivity',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 1,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin', 'broker'],
      description: 'Daily document submission volume'
    },
    {
      id: 'rachel-avg-response-time',
      kpiName: 'Avg Response Time',
      currentValue: '4.2',
      previousValue: '5.1',
      target: '4.0',
      unit: 'hours',
      category: 'efficiency',
      trend: 'improving',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 2,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin', 'broker'],
      description: 'Average underwriting response time'
    },
    {
      id: 'rachel-quote-success-rate',
      kpiName: 'Quote Success Rate',
      currentValue: '87.5',
      previousValue: '84.2',
      target: '90.0',
      unit: '%',
      category: 'performance',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 3,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin', 'broker'],
      description: 'Quote approval and conversion rate'
    },
    {
      id: 'rachel-active-submissions',
      kpiName: 'Active Submissions',
      currentValue: commercialSubmissions.length.toString(),
      previousValue: Math.max(0, commercialSubmissions.length - 1).toString(),
      target: '8',
      unit: 'items',
      category: 'workflow',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 4,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Currently active underwriting submissions'
    },

    // ===== INSIGHTS TAB (Priority 5-25) =====
    {
      id: 'rachel-underwriting-accuracy',
      kpiName: 'Underwriting Accuracy',
      currentValue: '96.8',
      previousValue: '94.3',
      target: '97.5',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 5,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Accuracy of underwriting decisions and risk assessments'
    },
    {
      id: 'rachel-risk-assessment-quality',
      kpiName: 'Risk Assessment Quality',
      currentValue: '94.2',
      previousValue: '91.7',
      target: '95.0',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 6,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Quality score of risk assessment analyses'
    },
    {
      id: 'rachel-cope-analysis-depth',
      kpiName: 'COPE Analysis Depth',
      currentValue: '8.6',
      previousValue: '8.1',
      target: '9.0',
      unit: 'score',
      category: 'analysis',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 7,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Depth and thoroughness of COPE analysis'
    },
    {
      id: 'rachel-portfolio-performance',
      kpiName: 'Portfolio Performance',
      currentValue: '12.4',
      previousValue: '11.8',
      target: '13.0',
      unit: '%',
      category: 'business',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 8,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Underwritten portfolio performance metrics'
    },
    {
      id: 'rachel-market-analysis',
      kpiName: 'Market Analysis Score',
      currentValue: '87.9',
      previousValue: '85.2',
      target: '90.0',
      unit: '%',
      category: 'analysis',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 9,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Market conditions analysis accuracy'
    },
    {
      id: 'rachel-document-processing-speed',
      kpiName: 'Document Processing Speed',
      currentValue: '18.5',
      previousValue: '22.1',
      target: '15.0',
      unit: 'minutes',
      category: 'efficiency',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 10,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Average document processing time'
    },
    {
      id: 'rachel-automation-rate',
      kpiName: 'Automation Rate',
      currentValue: '78.3',
      previousValue: '74.1',
      target: '82.0',
      unit: '%',
      category: 'productivity',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 11,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Percentage of automated processing'
    },
    {
      id: 'rachel-exception-handling',
      kpiName: 'Exception Handling',
      currentValue: '92.7',
      previousValue: '89.4',
      target: '95.0',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 12,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Success rate in handling exceptions'
    },
    {
      id: 'rachel-compliance-adherence',
      kpiName: 'Compliance Adherence',
      currentValue: '98.1',
      previousValue: '97.3',
      target: '99.0',
      unit: '%',
      category: 'governance',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 13,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Regulatory compliance adherence rate'
    },
    {
      id: 'rachel-data-extraction-accuracy',
      kpiName: 'Data Extraction Accuracy',
      currentValue: '95.8',
      previousValue: '93.6',
      target: '97.0',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 14,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Accuracy of automated data extraction'
    },
    {
      id: 'rachel-premium-optimization',
      kpiName: 'Premium Optimization',
      currentValue: '11.6',
      previousValue: '10.8',
      target: '12.5',
      unit: '%',
      category: 'business',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 15,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Premium optimization effectiveness'
    },
    {
      id: 'rachel-referral-rate',
      kpiName: 'Referral Rate',
      currentValue: '8.2',
      previousValue: '9.1',
      target: '7.0',
      unit: '%',
      category: 'quality',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 16,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Rate of cases requiring manual review'
    },
    {
      id: 'rachel-turnaround-consistency',
      kpiName: 'Turnaround Consistency',
      currentValue: '94.3',
      previousValue: '91.8',
      target: '96.0',
      unit: '%',
      category: 'efficiency',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 17,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Consistency in meeting turnaround times'
    },
    {
      id: 'rachel-agent-collaboration',
      kpiName: 'Agent Collaboration Score',
      currentValue: '8.7',
      previousValue: '8.3',
      target: '9.0',
      unit: 'score',
      category: 'productivity',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 18,
      viewCategory: 'technical',
      personaRelevance: ['rachel', 'admin'],
      description: 'Effectiveness of agent collaboration workflows'
    },
    {
      id: 'rachel-customer-satisfaction',
      kpiName: 'Customer Satisfaction',
      currentValue: '91.4',
      previousValue: '88.7',
      target: '93.0',
      unit: '%',
      category: 'experience',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 19,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin', 'broker'],
      description: 'Customer satisfaction with underwriting services'
    },
    {
      id: 'rachel-roi-impact',
      kpiName: 'ROI Impact',
      currentValue: '312',
      previousValue: '285',
      target: '350',
      unit: '%',
      category: 'business',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 20,
      viewCategory: 'business',
      personaRelevance: ['rachel', 'admin'],
      description: 'Return on investment impact for underwriting automation'
    }
  ];
}

// ============================================================================
// JOHN STEVENS (IT Support) - 24 KPIs Total
// ============================================================================
export function generateComprehensiveJohnKpis(
  activities: any[] = []
): KpiData[] {
  const systemActivities = activities.filter((a: any) => 
    a.persona === 'john' || a.activity.toLowerCase().includes('system')
  );
  const openTickets = systemActivities.filter((a: any) => 
    a.status === 'open' || a.status === 'pending'
  );

  return [
    // ===== MAIN DASHBOARD (Priority 1-4) =====
    {
      id: 'john-ticket-resolution-time',
      kpiName: 'Ticket Resolution Time',
      currentValue: '2.4',
      previousValue: '2.8',
      target: '2.0',
      unit: 'hours',
      category: 'support',
      trend: 'improving',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 1,
      viewCategory: 'business',
      personaRelevance: ['john', 'admin'],
      description: 'Average time to resolve support tickets'
    },
    {
      id: 'john-system-uptime',
      kpiName: 'System Uptime',
      currentValue: '99.8',
      previousValue: '99.6',
      target: '99.9',
      unit: '%',
      category: 'reliability',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 2,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Overall system availability and uptime'
    },
    {
      id: 'john-security-incidents',
      kpiName: 'Security Incidents',
      currentValue: '2',
      previousValue: '5',
      target: '0',
      unit: 'incidents',
      category: 'security',
      trend: 'improving',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 3,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Number of security incidents this period'
    },
    {
      id: 'john-user-satisfaction',
      kpiName: 'User Satisfaction',
      currentValue: '96.4',
      previousValue: '94.7',
      target: '97.0',
      unit: '%',
      category: 'experience',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 4,
      viewCategory: 'business',
      personaRelevance: ['john', 'admin'],
      description: 'IT support user satisfaction score'
    },

    // ===== INSIGHTS TAB (Priority 5-25) =====
    {
      id: 'john-performance-metrics',
      kpiName: 'Performance Metrics',
      currentValue: '92.6',
      previousValue: '89.3',
      target: '95.0',
      unit: '%',
      category: 'performance',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 5,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Overall IT performance metrics composite score'
    },
    {
      id: 'john-infrastructure-health',
      kpiName: 'Infrastructure Health',
      currentValue: '94.8',
      previousValue: '92.1',
      target: '96.0',
      unit: '%',
      category: 'infrastructure',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 6,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Infrastructure health and stability score'
    },
    {
      id: 'john-security-posture',
      kpiName: 'Security Posture',
      currentValue: '97.2',
      previousValue: '95.8',
      target: '98.0',
      unit: '%',
      category: 'security',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 7,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Comprehensive security posture assessment'
    },
    {
      id: 'john-capacity-planning',
      kpiName: 'Capacity Planning Score',
      currentValue: '87.4',
      previousValue: '84.6',
      target: '90.0',
      unit: '%',
      category: 'planning',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 8,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'System capacity planning effectiveness'
    },
    {
      id: 'john-api-response-time',
      kpiName: 'API Response Time',
      currentValue: '142',
      previousValue: '158',
      target: '120',
      unit: 'ms',
      category: 'performance',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 9,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Average API response time performance'
    },
    {
      id: 'john-error-rate',
      kpiName: 'Error Rate',
      currentValue: '0.12',
      previousValue: '0.18',
      target: '0.10',
      unit: '%',
      category: 'quality',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 10,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'System-wide error rate monitoring'
    },
    {
      id: 'john-backup-success',
      kpiName: 'Backup Success Rate',
      currentValue: '99.2',
      previousValue: '98.7',
      target: '99.5',
      unit: '%',
      category: 'reliability',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 11,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Data backup success rate'
    },
    {
      id: 'john-network-performance',
      kpiName: 'Network Performance',
      currentValue: '96.3',
      previousValue: '94.8',
      target: '97.0',
      unit: '%',
      category: 'performance',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 12,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Network infrastructure performance metrics'
    },
    {
      id: 'john-database-performance',
      kpiName: 'Database Performance',
      currentValue: '91.7',
      previousValue: '88.9',
      target: '94.0',
      unit: '%',
      category: 'performance',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 13,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Database performance and optimization metrics'
    },
    {
      id: 'john-patch-compliance',
      kpiName: 'Patch Compliance',
      currentValue: '94.6',
      previousValue: '91.2',
      target: '97.0',
      unit: '%',
      category: 'security',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 14,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'System patch compliance rate'
    },
    {
      id: 'john-storage-utilization',
      kpiName: 'Storage Utilization',
      currentValue: '73.8',
      previousValue: '76.2',
      target: '70.0',
      unit: '%',
      category: 'infrastructure',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 15,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Storage utilization and optimization'
    },
    {
      id: 'john-disaster-recovery',
      kpiName: 'Disaster Recovery Score',
      currentValue: '93.4',
      previousValue: '90.8',
      target: '95.0',
      unit: '%',
      category: 'reliability',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 16,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'Disaster recovery preparedness score'
    },
    {
      id: 'john-automation-coverage',
      kpiName: 'Automation Coverage',
      currentValue: '82.1',
      previousValue: '78.6',
      target: '85.0',
      unit: '%',
      category: 'productivity',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 17,
      viewCategory: 'business',
      personaRelevance: ['john', 'admin'],
      description: 'IT operations automation coverage'
    },
    {
      id: 'john-cost-optimization',
      kpiName: 'Cost Optimization',
      currentValue: '1.2M',
      previousValue: '1.0M',
      target: '1.5M',
      unit: 'USD',
      category: 'business',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 18,
      viewCategory: 'business',
      personaRelevance: ['john', 'admin'],
      description: 'IT cost optimization savings'
    },
    {
      id: 'john-change-success-rate',
      kpiName: 'Change Success Rate',
      currentValue: '96.8',
      previousValue: '94.3',
      target: '98.0',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 19,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'IT change management success rate'
    },
    {
      id: 'john-monitoring-coverage',
      kpiName: 'Monitoring Coverage',
      currentValue: '98.6',
      previousValue: '96.4',
      target: '99.0',
      unit: '%',
      category: 'monitoring',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 20,
      viewCategory: 'technical',
      personaRelevance: ['john', 'admin'],
      description: 'System monitoring coverage completeness'
    }
  ];
}

// ============================================================================
// BROKER - 24 KPIs Total
// ============================================================================
export function generateComprehensiveBrokerKpis(
  emails: any[] = [],
  activities: any[] = [],
  submissions: any[] = []
): KpiData[] {
  const brokerEmails = emails.filter((e: any) => e.persona === 'broker' || e.fromEmail?.includes('mike'));
  const brokerActivities = activities.filter((a: any) => a.persona === 'broker');
  const brokerSubmissions = submissions.filter((s: any) => s.brokerName?.includes('Mike') || s.brokerName?.includes('Stateline'));

  return [
    // ===== MAIN DASHBOARD (Priority 1-4) =====
    {
      id: 'broker-client-interactions',
      kpiName: 'Client Interactions',
      currentValue: brokerEmails.length.toString(),
      previousValue: Math.max(0, brokerEmails.length - 3).toString(),
      target: '25',
      unit: 'interactions',
      category: 'productivity',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 1,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Total client interactions and communications'
    },
    {
      id: 'broker-policy-conversions',
      kpiName: 'Policy Conversions',
      currentValue: '14.2',
      previousValue: '12.8',
      target: '16.0',
      unit: '%',
      category: 'performance',
      trend: 'up',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 2,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Quote to policy conversion rate'
    },
    {
      id: 'broker-revenue-generation',
      kpiName: 'Revenue Generation',
      currentValue: '2.8M',
      previousValue: '2.4M',
      target: '3.2M',
      unit: 'USD',
      category: 'business',
      trend: 'improving',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 3,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Total revenue generated through platform'
    },
    {
      id: 'broker-quote-turnaround',
      kpiName: 'Quote Turnaround',
      currentValue: '4.2',
      previousValue: '5.1',
      target: '3.5',
      unit: 'hours',
      category: 'efficiency',
      trend: 'improving',
      context: 'main_dashboard',
      displayContext: 'main',
      priority: 4,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin', 'rachel'],
      description: 'Average quote turnaround time'
    },

    // ===== INSIGHTS TAB (Priority 5-25) =====
    {
      id: 'broker-market-performance',
      kpiName: 'Market Performance',
      currentValue: '87.3',
      previousValue: '84.1',
      target: '90.0',
      unit: '%',
      category: 'business',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 5,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Overall market performance score'
    },
    {
      id: 'broker-client-retention',
      kpiName: 'Client Retention',
      currentValue: '91.6',
      previousValue: '89.2',
      target: '93.0',
      unit: '%',
      category: 'business',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 6,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Client retention and loyalty metrics'
    },
    {
      id: 'broker-cross-selling-success',
      kpiName: 'Cross-selling Success',
      currentValue: '23.7',
      previousValue: '21.4',
      target: '26.0',
      unit: '%',
      category: 'business',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 7,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Success rate in cross-selling additional products'
    },
    {
      id: 'broker-regional-analytics',
      kpiName: 'Regional Analytics Score',
      currentValue: '8.4',
      previousValue: '7.9',
      target: '9.0',
      unit: 'score',
      category: 'analysis',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 8,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Regional market analytics effectiveness'
    },
    {
      id: 'broker-proposal-quality',
      kpiName: 'Proposal Quality',
      currentValue: '93.8',
      previousValue: '91.2',
      target: '95.0',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 9,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Quality score of generated proposals'
    },
    {
      id: 'broker-competitive-analysis',
      kpiName: 'Competitive Analysis',
      currentValue: '86.4',
      previousValue: '83.7',
      target: '88.0',
      unit: '%',
      category: 'analysis',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 10,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Competitive market analysis effectiveness'
    },
    {
      id: 'broker-lead-conversion',
      kpiName: 'Lead Conversion Rate',
      currentValue: '18.6',
      previousValue: '16.8',
      target: '20.0',
      unit: '%',
      category: 'performance',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 11,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Lead to opportunity conversion rate'
    },
    {
      id: 'broker-customer-satisfaction',
      kpiName: 'Customer Satisfaction',
      currentValue: '92.3',
      previousValue: '89.1',
      target: '95.0',
      unit: '%',
      category: 'experience',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 12,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin', 'rachel'],
      description: 'Overall customer satisfaction score'
    },
    {
      id: 'broker-pipeline-velocity',
      kpiName: 'Pipeline Velocity',
      currentValue: '6.8',
      previousValue: '7.3',
      target: '6.0',
      unit: 'days',
      category: 'efficiency',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 13,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Average time to move through sales pipeline'
    },
    {
      id: 'broker-renewal-rate',
      kpiName: 'Renewal Rate',
      currentValue: '88.4',
      previousValue: '85.9',
      target: '90.0',
      unit: '%',
      category: 'business',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 14,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Policy renewal success rate'
    },
    {
      id: 'broker-digital-engagement',
      kpiName: 'Digital Engagement',
      currentValue: '74.6',
      previousValue: '71.2',
      target: '78.0',
      unit: '%',
      category: 'technology',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 15,
      viewCategory: 'technical',
      personaRelevance: ['broker', 'admin'],
      description: 'Digital platform engagement metrics'
    },
    {
      id: 'broker-processing-speed',
      kpiName: 'Processing Speed',
      currentValue: '4.2',
      previousValue: '5.1',
      target: '3.5',
      unit: 'hours',
      category: 'efficiency',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 16,
      viewCategory: 'technical',
      personaRelevance: ['broker', 'admin', 'rachel'],
      description: 'Average processing speed for submissions'
    },
    {
      id: 'broker-documentation-quality',
      kpiName: 'Documentation Quality',
      currentValue: '91.7',
      previousValue: '88.9',
      target: '94.0',
      unit: '%',
      category: 'quality',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 17,
      viewCategory: 'technical',
      personaRelevance: ['broker', 'admin'],
      description: 'Quality of submitted documentation'
    },
    {
      id: 'broker-communication-efficiency',
      kpiName: 'Communication Efficiency',
      currentValue: '89.3',
      previousValue: '86.7',
      target: '92.0',
      unit: '%',
      category: 'efficiency',
      trend: 'up',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 18,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Efficiency of client communication workflows'
    },
    {
      id: 'broker-risk-assessment-speed',
      kpiName: 'Risk Assessment Speed',
      currentValue: '32',
      previousValue: '38',
      target: '28',
      unit: 'minutes',
      category: 'efficiency',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 19,
      viewCategory: 'technical',
      personaRelevance: ['broker', 'admin', 'rachel'],
      description: 'Speed of risk assessment completion'
    },
    {
      id: 'broker-cost-savings',
      kpiName: 'Cost Savings',
      currentValue: '485K',
      previousValue: '428K',
      target: '550K',
      unit: 'USD',
      category: 'business',
      trend: 'improving',
      context: 'insights_tab',
      displayContext: 'insights',
      priority: 20,
      viewCategory: 'business',
      personaRelevance: ['broker', 'admin'],
      description: 'Cost savings achieved through automation'
    }
  ];
}